<a href="https://colab.research.google.com/github/aysenaozcan/phyton_repo/blob/master/Da_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
a=[1,2,3,4,5]
b=[2,3,4,5,6]

ab=[]
for i in range(0,len(a)):
  ab.append(a[i]*b[i])
ab

[2, 6, 12, 20, 30]

In [96]:
#numpy
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])

a*b

array([ 2,  6, 12, 20, 30])

In [11]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])

a*b

array([ 2,  6, 12, 20, 30])

In [12]:
np.array([1,2,3,4,5,3.14])  #int, float

array([1.  , 2.  , 3.  , 4.  , 5.  , 3.14])

In [13]:
np.array([1,2,3,4,5,3.14,"elma"])

array(['1', '2', '3', '4', '5', '3.14', 'elma'], dtype='<U32')

In [18]:
np.array([1,2,3,4,5,3.14],dtype="float32") #float'a çevirir.

array([1.  , 2.  , 3.  , 4.  , 5.  , 3.14], dtype=float32)

In [19]:
np.array([1,2,3,4,5,3.14],dtype="int") #int'a çevirir

array([1, 2, 3, 4, 5, 3])

In [20]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones(10,dtype="int")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.ones((3,5),dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
c=np.full((2,10),5)  #Creates a 2×10 NumPy array where every element is 5.
c

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [24]:
np.arange(0,31,3) #Creates a NumPy array starting at 0, ending before 31, with a step of 3.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [26]:
np.linspace(0,10,23)

array([ 0.        ,  0.45454545,  0.90909091,  1.36363636,  1.81818182,
        2.27272727,  2.72727273,  3.18181818,  3.63636364,  4.09090909,
        4.54545455,  5.        ,  5.45454545,  5.90909091,  6.36363636,
        6.81818182,  7.27272727,  7.72727273,  8.18181818,  8.63636364,
        9.09090909,  9.54545455, 10.        ])

In [27]:
np.linspace(0,1,23)

array([0.        , 0.04545455, 0.09090909, 0.13636364, 0.18181818,
       0.22727273, 0.27272727, 0.31818182, 0.36363636, 0.40909091,
       0.45454545, 0.5       , 0.54545455, 0.59090909, 0.63636364,
       0.68181818, 0.72727273, 0.77272727, 0.81818182, 0.86363636,
       0.90909091, 0.95454545, 1.        ])

In [28]:
np.random.normal(10,4,(3,4))

array([[ 8.4386946 , 12.14210547,  7.26675798, 12.28466592],
       [12.3647656 ,  6.56212747, 17.18034007,  8.56563154],
       [ 7.04617026, 11.72223321,  8.33149468, 13.50360865]])

In [29]:
np.random.randint(0,10,(3,3))

array([[1, 8, 5],
       [3, 2, 8],
       [9, 4, 9]])

In [35]:
type(c)

numpy.ndarray

In [ ]:
# ndim: number of dimensions
# shape: array dimensions (size of each axis)
# size: total number of elements
# dtype: data type of the elements in the array

In [39]:
a=np.random.randint(10,size=10)
a

array([7, 5, 4, 9, 4, 3, 7, 6, 8, 8])

In [40]:
type(a)

numpy.ndarray

In [41]:
a.shape

(10,)

In [42]:
a.dtype

dtype('int64')

In [43]:
b=np.random.randint(10,size=(3,5))
b

array([[6, 3, 7, 2, 1],
       [7, 8, 5, 9, 2],
       [5, 6, 9, 7, 5]])

In [44]:
b.ndim

2

In [45]:
b.shape

(3, 5)

In [46]:
b.size

15

In [47]:
b.dtype

dtype('int64')

In [49]:
k=np.arange(1,10)
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
k.shape

(9,)

In [55]:
d=k.reshape((3,3))
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
k.ndim

1

In [57]:
d.ndim

2

In [58]:
k.size

9

In [61]:
dd=k.reshape((1,9))
dd

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
dd.ndim

2

In [63]:
ddd=k.reshape((9,1))
ddd

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [64]:
ddd.ndim

2

In [66]:
ddd.shape

(9, 1)

In [67]:
dd.shape

(1, 9)

In [68]:
dd

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
k.shape

(9,)

In [71]:
dd.shape

(1, 9)

In [72]:
dd.ndim

2

In [73]:
t_np=np.zeros((2,3,4))
t_np

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [74]:
t_np.ndim

3

In [75]:
t_np.shape

(2, 3, 4)

In [77]:
t_np.size

24

In [85]:
t_np

(2, 3, 4)

In [ ]:
t_np = t_np.shape

In [98]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [100]:
t=np.concatenate([x,y])
t

array([1, 2, 3, 4, 5, 6])

In [111]:
z=np.array([1,2,3,99,98,75,13,46])

In [105]:
q=np.concatenate([t,z])
q

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [107]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])

In [109]:
tu=np.concatenate([a,a], axis=1)
tu

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [121]:
a,b,c=np.split(z,[3,5])

In [116]:
a

array([1, 2, 3])

In [117]:
b

array([99, 98])

In [118]:
c

array([75, 13, 46])

In [125]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
alt,ust=np.vsplit(m,[1])  #msplit, hsplit
alt

array([[0, 1, 2, 3]])

In [137]:
ust

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [189]:
np.hsplit(m,[1])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]

In [190]:
a=[1,2,3,6,7,45,43,2]

In [197]:
a.sort

<function list.sort(*, key=None, reverse=False)>

In [199]:
t=np.sort(a)
t

array([ 1,  2,  2,  3,  6,  7, 43, 45])

In [202]:
m=np.random.normal(20,5,(3,3))
m

array([[25.77417704, 16.5304169 , 18.65057444],
       [22.69983605, 25.8896578 , 25.58490369],
       [13.80243205, 25.45236604, 22.7448774 ]])

In [203]:
np.sort(m,axis=0)

array([[13.80243205, 16.5304169 , 18.65057444],
       [22.69983605, 25.45236604, 22.7448774 ],
       [25.77417704, 25.8896578 , 25.58490369]])

In [204]:
m

array([[25.77417704, 16.5304169 , 18.65057444],
       [22.69983605, 25.8896578 , 25.58490369],
       [13.80243205, 25.45236604, 22.7448774 ]])

In [205]:
np.sort(m,axis=1)

array([[16.5304169 , 18.65057444, 25.77417704],
       [22.69983605, 25.58490369, 25.8896578 ],
       [13.80243205, 22.7448774 , 25.45236604]])

In [206]:
np.arange(16).reshape(1,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [210]:
x=np.array  ([[1,2,3], [4,5,6]])
y=np.array  ([1,2,3])

In [211]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [212]:
k.dtype

dtype('int64')

In [213]:
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
f=np.random.randint(10,size=12)
f

array([1, 7, 6, 5, 5, 5, 8, 9, 4, 8, 7, 7])

In [216]:
f[0]

np.int64(1)

In [217]:
f

array([1, 7, 6, 5, 5, 5, 8, 9, 4, 8, 7, 7])

In [218]:
a[0]=100

In [219]:
a

[100, 2, 3, 6, 7, 45, 43, 2]

In [220]:
a[-1]=69

In [221]:
a

[100, 2, 3, 6, 7, 45, 43, 69]